-- ============================================================================
-- Nanowork Agent Platform Schema
-- ============================================================================
-- This schema supports the multi-agent build orchestration system
-- Each user gets a single agent that orchestrates specialized build agents
-- for creating business plans, financial models, pitch decks, etc.

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

-- Enable pgvector for AI embeddings (agent memory)
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- AGENTS TABLE
-- ============================================================================
-- Core agent records - one agent per user

CREATE TABLE IF NOT EXISTS agents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'archived')),
  model TEXT NOT NULL DEFAULT 'claude-sonnet-4-20250514',
  system_prompt TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- One agent per user
  UNIQUE(user_id)
);

CREATE INDEX IF NOT EXISTS idx_agents_user_id ON agents(user_id);
CREATE INDEX IF NOT EXISTS idx_agents_status ON agents(status);

-- ============================================================================
-- GENERATED APPS TABLE
-- ============================================================================
-- Business ideas and apps generated by agents

CREATE TABLE IF NOT EXISTS generated_apps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  agent_id UUID REFERENCES agents(id) ON DELETE SET NULL,
  app_name TEXT NOT NULL,
  app_type TEXT NOT NULL,
  description TEXT,
  source_code TEXT,
  config JSONB,
  deployed_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'building', 'completed', 'deployed', 'failed')),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_generated_apps_user_id ON generated_apps(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_generated_apps_agent_id ON generated_apps(agent_id);
CREATE INDEX IF NOT EXISTS idx_generated_apps_status ON generated_apps(status);

-- ============================================================================
-- AGENT EXECUTIONS TABLE
-- ============================================================================
-- Track specialized agent task execution for each build

CREATE TABLE IF NOT EXISTS agent_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  build_id UUID NOT NULL REFERENCES generated_apps(id) ON DELETE CASCADE,
  agent_type TEXT NOT NULL CHECK (agent_type IN (
    'business_analyst',
    'financial_planner',
    'product_designer',
    'marketing',
    'legal',
    'technical_architect',
    'pitch'
  )),

  -- Execution status
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'completed', 'error')),
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  current_activity TEXT,

  -- Results
  result JSONB,
  error_message TEXT,

  -- Timing
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE(build_id, agent_type)
);

CREATE INDEX IF NOT EXISTS idx_agent_executions_build_id ON agent_executions(build_id);
CREATE INDEX IF NOT EXISTS idx_agent_executions_agent_type ON agent_executions(agent_type);
CREATE INDEX IF NOT EXISTS idx_agent_executions_status ON agent_executions(status);
CREATE INDEX IF NOT EXISTS idx_agent_executions_created_at ON agent_executions(created_at DESC);

-- ============================================================================
-- BUILD DOCUMENTS TABLE
-- ============================================================================
-- Documents generated by specialized agents

CREATE TABLE IF NOT EXISTS build_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  build_id UUID NOT NULL REFERENCES generated_apps(id) ON DELETE CASCADE,

  -- Document metadata
  document_type TEXT NOT NULL, -- agent_type that generated it
  title TEXT NOT NULL,
  content JSONB NOT NULL,

  -- Versioning
  version INTEGER DEFAULT 1,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_build_documents_build_id ON build_documents(build_id);
CREATE INDEX IF NOT EXISTS idx_build_documents_document_type ON build_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_build_documents_created_at ON build_documents(created_at DESC);

-- ============================================================================
-- BUILD SPREADSHEETS TABLE
-- ============================================================================
-- Financial models and data generated by financial planner agent

CREATE TABLE IF NOT EXISTS build_spreadsheets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  build_id UUID NOT NULL REFERENCES generated_apps(id) ON DELETE CASCADE,

  -- Spreadsheet metadata
  spreadsheet_type TEXT NOT NULL DEFAULT 'financial_model',
  name TEXT,
  data JSONB NOT NULL,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_build_spreadsheets_build_id ON build_spreadsheets(build_id);
CREATE INDEX IF NOT EXISTS idx_build_spreadsheets_created_at ON build_spreadsheets(created_at DESC);

-- ============================================================================
-- BUILD PITCH DECKS TABLE
-- ============================================================================
-- Investor pitch materials compiled from all agent outputs

CREATE TABLE IF NOT EXISTS build_pitch_decks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  build_id UUID NOT NULL REFERENCES generated_apps(id) ON DELETE CASCADE,

  -- Deck data compiled from all agents
  deck_data JSONB NOT NULL,

  -- Export formats
  pdf_url TEXT,
  pptx_url TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_build_pitch_decks_build_id ON build_pitch_decks(build_id);
CREATE INDEX IF NOT EXISTS idx_build_pitch_decks_created_at ON build_pitch_decks(created_at DESC);

-- ============================================================================
-- AGENT CONVERSATIONS TABLE
-- ============================================================================
-- Conversation threads with agents

CREATE TABLE IF NOT EXISTS agent_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT,
  messages JSONB NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived', 'deleted')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_conversations_agent_id ON agent_conversations(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_conversations_user_id ON agent_conversations(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_conversations_status ON agent_conversations(status);

-- ============================================================================
-- AGENT MEMORIES TABLE
-- ============================================================================
-- Vector-based memory storage for agents (RAG)

CREATE TABLE IF NOT EXISTS agent_memories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  memory_type TEXT NOT NULL CHECK (memory_type IN ('fact', 'preference', 'context', 'goal')),
  content TEXT NOT NULL,
  importance INTEGER NOT NULL DEFAULT 5 CHECK (importance BETWEEN 1 AND 10),
  embedding vector(1536),
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  accessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_memories_agent_id ON agent_memories(agent_id, importance DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memories_type ON agent_memories(memory_type);
CREATE INDEX IF NOT EXISTS idx_agent_memories_embedding ON agent_memories USING ivfflat (embedding vector_cosine_ops);

-- ============================================================================
-- AGENT TASKS TABLE
-- ============================================================================
-- Tasks assigned to or created by agents

CREATE TABLE IF NOT EXISTS agent_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  task_type TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'failed', 'cancelled')),
  priority INTEGER NOT NULL DEFAULT 5 CHECK (priority BETWEEN 1 AND 10),
  input_data JSONB,
  output_data JSONB,
  error_message TEXT,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  due_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_tasks_agent_id ON agent_tasks(agent_id, status, priority DESC);
CREATE INDEX IF NOT EXISTS idx_agent_tasks_status ON agent_tasks(status, due_at);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_apps ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE build_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE build_spreadsheets ENABLE ROW LEVEL SECURITY;
ALTER TABLE build_pitch_decks ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_tasks ENABLE ROW LEVEL SECURITY;

-- Users can only see their own agents
CREATE POLICY agents_user_policy ON agents
  FOR ALL USING (auth.uid() = user_id);

-- Users can manage their own generated apps
CREATE POLICY generated_apps_user_policy ON generated_apps
  FOR ALL USING (auth.uid() = user_id);

-- Users can view agent executions for their builds
CREATE POLICY agent_executions_user_policy ON agent_executions
  FOR SELECT USING (
    build_id IN (
      SELECT id FROM generated_apps WHERE agent_id IN (
        SELECT id FROM agents WHERE user_id = auth.uid()
      )
    )
  );

-- System can manage agent executions
CREATE POLICY agent_executions_system_policy ON agent_executions
  FOR INSERT WITH CHECK (true);

CREATE POLICY agent_executions_update_policy ON agent_executions
  FOR UPDATE USING (true);

-- Users can view documents for their builds
CREATE POLICY build_documents_user_policy ON build_documents
  FOR SELECT USING (
    build_id IN (
      SELECT id FROM generated_apps WHERE agent_id IN (
        SELECT id FROM agents WHERE user_id = auth.uid()
      )
    )
  );

-- System can manage documents
CREATE POLICY build_documents_system_policy ON build_documents
  FOR ALL USING (true);

-- Users can view spreadsheets for their builds
CREATE POLICY build_spreadsheets_user_policy ON build_spreadsheets
  FOR SELECT USING (
    build_id IN (
      SELECT id FROM generated_apps WHERE agent_id IN (
        SELECT id FROM agents WHERE user_id = auth.uid()
      )
    )
  );

-- System can manage spreadsheets
CREATE POLICY build_spreadsheets_system_policy ON build_spreadsheets
  FOR ALL USING (true);

-- Users can view pitch decks for their builds
CREATE POLICY build_pitch_decks_user_policy ON build_pitch_decks
  FOR SELECT USING (
    build_id IN (
      SELECT id FROM generated_apps WHERE agent_id IN (
        SELECT id FROM agents WHERE user_id = auth.uid()
      )
    )
  );

-- System can manage pitch decks
CREATE POLICY build_pitch_decks_system_policy ON build_pitch_decks
  FOR ALL USING (true);

-- Users can manage their own conversations
CREATE POLICY agent_conversations_user_policy ON agent_conversations
  FOR ALL USING (auth.uid() = user_id);

-- Users can manage memories for their own agents
CREATE POLICY agent_memories_user_policy ON agent_memories
  FOR ALL USING (
    EXISTS (SELECT 1 FROM agents WHERE agents.id = agent_memories.agent_id AND agents.user_id = auth.uid())
  );

-- Users can view tasks for their own agents
CREATE POLICY agent_tasks_user_policy ON agent_tasks
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM agents WHERE agents.id = agent_tasks.agent_id AND agents.user_id = auth.uid())
  );

-- ============================================================================
-- UPDATED_AT TRIGGERS
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_agents_updated_at BEFORE UPDATE ON agents
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_generated_apps_updated_at BEFORE UPDATE ON generated_apps
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_agent_executions_updated_at BEFORE UPDATE ON agent_executions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_build_documents_updated_at BEFORE UPDATE ON build_documents
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_build_spreadsheets_updated_at BEFORE UPDATE ON build_spreadsheets
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_build_pitch_decks_updated_at BEFORE UPDATE ON build_pitch_decks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_agent_conversations_updated_at BEFORE UPDATE ON agent_conversations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_agent_tasks_updated_at BEFORE UPDATE ON agent_tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
