import { Router, Response } from 'express';
import { requireUserAuth } from '../middleware/auth';
import { AuthenticatedRequest } from '../types';
import { getOrchestrator } from '../services/agentOrchestrator';
import { getSupabase } from '../services/supabase';

const router = Router();

/**
 * POST /agent-orchestrator/builds/:buildId/start
 * Start agent orchestration for a build
 */
router.post('/builds/:buildId/start', requireUserAuth, async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Verify build belongs to user
    const { data: build, error } = await getSupabase()
      .from('generated_apps')
      .select('*')
      .eq('id', buildId)
      .eq('agent_id', req.agent.id)
      .single();

    if (error || !build) {
      res.status(404).json({ error: 'Build not found' });
      return;
    }

    // Start orchestration
    const orchestrator = getOrchestrator();

    // Don't await - let it run in background
    orchestrator.startBuild(buildId, build.prompt || build.name)
      .catch(err => {
        console.error('Orchestration error:', err);
      });

    res.json({
      success: true,
      message: 'Agent orchestration started',
    });
  } catch (error) {
    console.error('Start orchestration error:', error);
    res.status(500).json({
      error: 'Failed to start orchestration',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
});

/**
 * GET /agent-orchestrator/builds/:buildId/status
 * Get current status of all agents for a build
 */
router.get('/builds/:buildId/status', requireUserAuth, async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Verify build belongs to user
    const { data: build, error } = await getSupabase()
      .from('generated_apps')
      .select('*')
      .eq('id', buildId)
      .eq('agent_id', req.agent.id)
      .single();

    if (error || !build) {
      res.status(404).json({ error: 'Build not found' });
      return;
    }

    // Get status
    const orchestrator = getOrchestrator();
    const tasks = await orchestrator.getBuildStatus(buildId);

    res.json({
      tasks,
    });
  } catch (error) {
    console.error('Get status error:', error);
    res.status(500).json({
      error: 'Failed to get status',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
});

/**
 * GET /agent-orchestrator/builds/:buildId/documents
 * Get all documents generated by agents
 */
router.get('/builds/:buildId/documents', requireUserAuth, async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Verify build belongs to user
    const { data: build, error: buildError } = await getSupabase()
      .from('generated_apps')
      .select('*')
      .eq('id', buildId)
      .eq('agent_id', req.agent.id)
      .single();

    if (buildError || !build) {
      res.status(404).json({ error: 'Build not found' });
      return;
    }

    // Get documents
    const { data: documents, error: docsError } = await getSupabase()
      .from('build_documents')
      .select('*')
      .eq('build_id', buildId)
      .order('created_at', { ascending: true });

    if (docsError) {
      throw docsError;
    }

    res.json({
      documents: documents || [],
    });
  } catch (error) {
    console.error('Get documents error:', error);
    res.status(500).json({
      error: 'Failed to get documents',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
});

/**
 * GET /agent-orchestrator/builds/:buildId/spreadsheet
 * Get financial spreadsheet data
 */
router.get('/builds/:buildId/spreadsheet', requireUserAuth, async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Verify build belongs to user
    const { data: build, error: buildError } = await getSupabase()
      .from('generated_apps')
      .select('*')
      .eq('id', buildId)
      .eq('agent_id', req.agent.id)
      .single();

    if (buildError || !build) {
      res.status(404).json({ error: 'Build not found' });
      return;
    }

    // Get spreadsheet
    const { data: spreadsheet, error: spreadsheetError } = await getSupabase()
      .from('build_spreadsheets')
      .select('*')
      .eq('build_id', buildId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (spreadsheetError && spreadsheetError.code !== 'PGRST116') {
      throw spreadsheetError;
    }

    res.json({
      spreadsheet: spreadsheet || null,
    });
  } catch (error) {
    console.error('Get spreadsheet error:', error);
    res.status(500).json({
      error: 'Failed to get spreadsheet',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
});

/**
 * GET /agent-orchestrator/builds/:buildId/pitch-deck
 * Get pitch deck data
 */
router.get('/builds/:buildId/pitch-deck', requireUserAuth, async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Verify build belongs to user
    const { data: build, error: buildError } = await getSupabase()
      .from('generated_apps')
      .select('*')
      .eq('id', buildId)
      .eq('agent_id', req.agent.id)
      .single();

    if (buildError || !build) {
      res.status(404).json({ error: 'Build not found' });
      return;
    }

    // Get pitch deck
    const { data: pitchDeck, error: pitchError } = await getSupabase()
      .from('build_pitch_decks')
      .select('*')
      .eq('build_id', buildId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (pitchError && pitchError.code !== 'PGRST116') {
      throw pitchError;
    }

    res.json({
      pitchDeck: pitchDeck || null,
    });
  } catch (error) {
    console.error('Get pitch deck error:', error);
    res.status(500).json({
      error: 'Failed to get pitch deck',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
});

export default router;
