#!/usr/bin/env bash

# Git Hooks Installer for Auto-Commit System
# Safely installs custom git hooks with backup and restoration capabilities

set -euo pipefail

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
GIT_HOOKS_DIR="$PROJECT_ROOT/.git/hooks"
BACKUP_DIR="$GIT_HOOKS_DIR/backups"
CONFIG_DIR="$PROJECT_ROOT/.claude/auto-commit"

# Hook files
HOOKS=("post-commit" "post-checkout" "post-merge")

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if we're in a git repository
check_git_repo() {
    if [ ! -d "$PROJECT_ROOT/.git" ]; then
        log_error "Not a git repository. Please run this from within the nanowork-web project."
        exit 1
    fi
}

# Create necessary directories
setup_directories() {
    log_info "Setting up directories..."

    mkdir -p "$BACKUP_DIR"
    mkdir -p "$CONFIG_DIR"

    # Create config file if it doesn't exist
    if [ ! -f "$CONFIG_DIR/config.json" ]; then
        cat > "$CONFIG_DIR/config.json" <<EOF
{
  "enabled": false,
  "autoCommitOnCheckout": false,
  "autoCommitOnMerge": false,
  "fsmonitorEnabled": false,
  "hookVersion": "1.0.0",
  "installedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF
        log_success "Created default config at $CONFIG_DIR/config.json"
    fi
}

# Backup existing hook
backup_hook() {
    local hook_name=$1
    local hook_path="$GIT_HOOKS_DIR/$hook_name"

    if [ -f "$hook_path" ] && [ ! -L "$hook_path" ]; then
        local timestamp=$(date +"%Y%m%d_%H%M%S")
        local backup_path="$BACKUP_DIR/${hook_name}.${timestamp}.backup"

        cp "$hook_path" "$backup_path"
        log_success "Backed up existing $hook_name to $backup_path"
        return 0
    fi

    return 1
}

# Install a single hook
install_hook() {
    local hook_name=$1
    local hook_source="$SCRIPT_DIR/${hook_name}.sample"
    local hook_dest="$GIT_HOOKS_DIR/$hook_name"

    log_info "Installing $hook_name hook..."

    # Backup existing hook if present
    backup_hook "$hook_name" || log_info "No existing $hook_name hook to backup"

    # Copy hook from sample
    if [ -f "$hook_source" ]; then
        cp "$hook_source" "$hook_dest"
        chmod +x "$hook_dest"
        log_success "Installed $hook_name hook"
    else
        log_warning "Hook sample not found: $hook_source"
        return 1
    fi
}

# Create wrapper hook that chains existing hooks
create_wrapper_hook() {
    local hook_name=$1
    local hook_path="$GIT_HOOKS_DIR/$hook_name"
    local backup_path="$BACKUP_DIR/${hook_name}.original"

    # If there's already a hook and it's not our wrapper
    if [ -f "$hook_path" ] && ! grep -q "AUTO-COMMIT-WRAPPER" "$hook_path" 2>/dev/null; then
        cp "$hook_path" "$backup_path"
        log_info "Saved original $hook_name to $backup_path"
    fi

    # Create wrapper that calls both original and our hook
    cat > "$hook_path" <<'HOOK_EOF'
#!/usr/bin/env bash
# AUTO-COMMIT-WRAPPER: This hook was generated by the auto-commit system

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BACKUP_DIR="$SCRIPT_DIR/backups"
HOOK_NAME="$(basename "${BASH_SOURCE[0]}")"
ORIGINAL_HOOK="$BACKUP_DIR/${HOOK_NAME}.original"

# Run original hook if it exists
if [ -f "$ORIGINAL_HOOK" ] && [ -x "$ORIGINAL_HOOK" ]; then
    "$ORIGINAL_HOOK" "$@"
fi

# Run our auto-commit hook
AUTO_COMMIT_HOOK="$PROJECT_ROOT/scripts/auto-commit/hooks/${HOOK_NAME}.sample"
if [ -f "$AUTO_COMMIT_HOOK" ] && [ -x "$AUTO_COMMIT_HOOK" ]; then
    "$AUTO_COMMIT_HOOK" "$@"
fi

exit 0
HOOK_EOF

    chmod +x "$hook_path"
}

# Install all hooks
install_all_hooks() {
    log_info "Installing auto-commit git hooks..."

    for hook in "${HOOKS[@]}"; do
        if [ -f "$SCRIPT_DIR/${hook}.sample" ]; then
            create_wrapper_hook "$hook"
            log_success "Installed wrapper for $hook"
        else
            log_warning "Sample hook not found: ${hook}.sample"
        fi
    done

    log_success "All hooks installed successfully!"
}

# Uninstall hooks
uninstall_hooks() {
    log_info "Uninstalling auto-commit git hooks..."

    for hook in "${HOOKS[@]}"; do
        local hook_path="$GIT_HOOKS_DIR/$hook"
        local backup_path="$BACKUP_DIR/${hook}.original"

        if [ -f "$hook_path" ] && grep -q "AUTO-COMMIT-WRAPPER" "$hook_path" 2>/dev/null; then
            # Restore original hook if it exists
            if [ -f "$backup_path" ]; then
                cp "$backup_path" "$hook_path"
                chmod +x "$hook_path"
                log_success "Restored original $hook hook"
            else
                rm "$hook_path"
                log_success "Removed $hook hook"
            fi
        fi
    done

    log_success "Hooks uninstalled successfully!"
}

# List installed hooks
list_hooks() {
    log_info "Installed auto-commit hooks:"
    echo ""

    for hook in "${HOOKS[@]}"; do
        local hook_path="$GIT_HOOKS_DIR/$hook"

        if [ -f "$hook_path" ]; then
            if grep -q "AUTO-COMMIT-WRAPPER" "$hook_path" 2>/dev/null; then
                echo -e "  ${GREEN}✓${NC} $hook (auto-commit wrapper installed)"
            else
                echo -e "  ${YELLOW}!${NC} $hook (custom hook, not managed by auto-commit)"
            fi
        else
            echo -e "  ${RED}✗${NC} $hook (not installed)"
        fi
    done

    echo ""

    # Show backups
    if [ -d "$BACKUP_DIR" ] && [ "$(ls -A "$BACKUP_DIR" 2>/dev/null)" ]; then
        log_info "Available backups in $BACKUP_DIR:"
        ls -lh "$BACKUP_DIR" | tail -n +2 | awk '{print "  " $9 " (" $5 ", " $6 " " $7 ")"}'
    fi
}

# Restore a specific backup
restore_backup() {
    local backup_file=$1

    if [ ! -f "$BACKUP_DIR/$backup_file" ]; then
        log_error "Backup file not found: $backup_file"
        exit 1
    fi

    # Extract hook name from backup filename
    local hook_name=$(echo "$backup_file" | sed 's/\..*//')
    local hook_path="$GIT_HOOKS_DIR/$hook_name"

    cp "$BACKUP_DIR/$backup_file" "$hook_path"
    chmod +x "$hook_path"

    log_success "Restored $hook_name from backup: $backup_file"
}

# Enable/disable auto-commit
toggle_auto_commit() {
    local action=$1
    local config_file="$CONFIG_DIR/config.json"

    if [ ! -f "$config_file" ]; then
        log_error "Config file not found. Please run 'install' first."
        exit 1
    fi

    if [ "$action" = "enable" ]; then
        # Update config to enable auto-commit
        local temp_file=$(mktemp)
        jq '.enabled = true' "$config_file" > "$temp_file" && mv "$temp_file" "$config_file"
        log_success "Auto-commit enabled"
    elif [ "$action" = "disable" ]; then
        # Update config to disable auto-commit
        local temp_file=$(mktemp)
        jq '.enabled = false' "$config_file" > "$temp_file" && mv "$temp_file" "$config_file"
        log_success "Auto-commit disabled"
    fi
}

# Show usage
show_usage() {
    cat <<EOF
Git Hooks Installer for Auto-Commit System

Usage: $0 <command> [options]

Commands:
    install         Install auto-commit git hooks
    uninstall       Remove auto-commit git hooks
    list            List installed hooks and backups
    enable          Enable auto-commit functionality
    disable         Disable auto-commit functionality
    restore <file>  Restore a specific backup file
    help            Show this help message

Examples:
    $0 install              # Install all hooks
    $0 list                 # Show installed hooks
    $0 enable               # Enable auto-commit
    $0 disable              # Disable auto-commit
    $0 uninstall            # Remove all hooks
    $0 restore post-commit.20240524_120000.backup

Environment:
    Project Root:  $PROJECT_ROOT
    Git Hooks:     $GIT_HOOKS_DIR
    Backups:       $BACKUP_DIR
    Config:        $CONFIG_DIR

EOF
}

# Main execution
main() {
    local command=${1:-help}

    case "$command" in
        install)
            check_git_repo
            setup_directories
            install_all_hooks
            log_info "Run '$0 enable' to activate auto-commit functionality"
            ;;
        uninstall)
            check_git_repo
            uninstall_hooks
            ;;
        list)
            check_git_repo
            list_hooks
            ;;
        enable)
            check_git_repo
            toggle_auto_commit "enable"
            ;;
        disable)
            check_git_repo
            toggle_auto_commit "disable"
            ;;
        restore)
            check_git_repo
            if [ -z "${2:-}" ]; then
                log_error "Please specify a backup file to restore"
                exit 1
            fi
            restore_backup "$2"
            ;;
        help|--help|-h)
            show_usage
            ;;
        *)
            log_error "Unknown command: $command"
            echo ""
            show_usage
            exit 1
            ;;
    esac
}

# Run main with all arguments
main "$@"
