import { Router, Response } from 'express';
import { requireUserAuth } from '../middleware/auth';
import { verifyBuildOwnership } from '../middleware/buildOwnership';
import { AuthenticatedRequest } from '../types';
import { getOrchestrator } from '../services/agentOrchestrator';
import { getSupabase } from '../services/supabase';
import { rateLimitAgentOrchestrator } from '../middleware/rateLimiting';
import { checkAgentOrchestratorCredits, deductOperationCredits } from '../middleware/costProtection';

const router = Router();

/**
 * POST /agent-orchestrator/builds/:buildId/start
 * Start agent orchestration for a build
 */
router.post('/builds/:buildId/start', requireUserAuth, rateLimitAgentOrchestrator, checkAgentOrchestratorCredits, verifyBuildOwnership, (async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Get build (ownership already verified by middleware)
    const { data: build, error } = await getSupabase()
      .from('generated_apps')
      .select('*')
      .eq('id', buildId)
      .single();

    if (error || !build) {
      res.status(404).json({ error: 'Build not found' });
      return;
    }

    // Deduct credits upfront since orchestration runs in background
    if (req.user?.id && (req as any).requiredCredits) {
      await deductOperationCredits(
        req.user.id,
        (req as any).requiredCredits,
        'agent_orchestrator',
        { build_id: buildId }
      ).catch(err => console.error('Failed to deduct credits:', err));
    }

    // Start orchestration
    const orchestrator = getOrchestrator();

    // Don't await - let it run in background
    orchestrator.startBuild(buildId, build.prompt || build.name)
      .catch(err => {
        console.error('Orchestration error:', err);
      });

    res.json({
      success: true,
      message: 'Agent orchestration started',
    });
  } catch (error) {
    console.error('Start orchestration error:', error);
    res.status(500).json({
      error: 'Failed to start orchestration',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
}) as any);

/**
 * GET /agent-orchestrator/builds/:buildId/status
 * Get current status of all agents for a build
 */
router.get('/builds/:buildId/status', requireUserAuth, verifyBuildOwnership, (async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Get status
    const orchestrator = getOrchestrator();
    const tasks = await orchestrator.getBuildStatus(buildId);

    res.json({
      tasks,
    });
  } catch (error) {
    console.error('Get status error:', error);
    res.status(500).json({
      error: 'Failed to get status',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
}) as any);

/**
 * GET /agent-orchestrator/documents
 * Get all documents across all builds for the user
 */
router.get('/documents', requireUserAuth, (async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    // Get all builds for the user
    const { data: builds, error: buildsError } = await getSupabase()
      .from('generated_apps')
      .select('id, name')
      .eq('agent_id', req.agent.id);

    if (buildsError) {
      throw buildsError;
    }

    const buildIds = builds?.map(b => b.id) || [];

    if (buildIds.length === 0) {
      res.json({ documents: [] });
      return;
    }

    // Get all documents for these builds
    const { data: documents, error: docsError } = await getSupabase()
      .from('build_documents')
      .select('*')
      .in('build_id', buildIds)
      .order('created_at', { ascending: false });

    if (docsError) {
      throw docsError;
    }

    // Enrich documents with build names
    const enrichedDocuments = (documents || []).map(doc => {
      const build = builds?.find(b => b.id === doc.build_id);
      return {
        ...doc,
        build_name: build?.name || 'Unknown Build',
      };
    });

    res.json({
      documents: enrichedDocuments,
    });
  } catch (error) {
    console.error('Get all documents error:', error);
    res.status(500).json({
      error: 'Failed to get documents',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
}) as any);

/**
 * GET /agent-orchestrator/builds/:buildId/documents
 * Get all documents generated by agents
 */
router.get('/builds/:buildId/documents', requireUserAuth, verifyBuildOwnership, (async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Get documents
    const { data: documents, error: docsError } = await getSupabase()
      .from('build_documents')
      .select('*')
      .eq('build_id', buildId)
      .order('created_at', { ascending: true });

    if (docsError) {
      throw docsError;
    }

    res.json({
      documents: documents || [],
    });
  } catch (error) {
    console.error('Get documents error:', error);
    res.status(500).json({
      error: 'Failed to get documents',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
}) as any);

/**
 * GET /agent-orchestrator/builds/:buildId/spreadsheets
 * Get all spreadsheets generated by agents
 */
router.get('/builds/:buildId/spreadsheets', requireUserAuth, verifyBuildOwnership, (async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Get all spreadsheets
    const { data: spreadsheets, error: spreadsheetsError } = await getSupabase()
      .from('build_spreadsheets')
      .select('*')
      .eq('build_id', buildId)
      .order('created_at', { ascending: true });

    if (spreadsheetsError) {
      throw spreadsheetsError;
    }

    res.json({
      spreadsheets: spreadsheets || [],
    });
  } catch (error) {
    console.error('Get spreadsheets error:', error);
    res.status(500).json({
      error: 'Failed to get spreadsheets',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
}) as any);

/**
 * GET /agent-orchestrator/builds/:buildId/spreadsheet
 * Get financial spreadsheet data (single - for backward compatibility)
 */
router.get('/builds/:buildId/spreadsheet', requireUserAuth, verifyBuildOwnership, (async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Get spreadsheet
    const { data: spreadsheet, error: spreadsheetError } = await getSupabase()
      .from('build_spreadsheets')
      .select('*')
      .eq('build_id', buildId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (spreadsheetError && spreadsheetError.code !== 'PGRST116') {
      throw spreadsheetError;
    }

    res.json({
      spreadsheet: spreadsheet || null,
    });
  } catch (error) {
    console.error('Get spreadsheet error:', error);
    res.status(500).json({
      error: 'Failed to get spreadsheet',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
}) as any);

/**
 * GET /agent-orchestrator/builds/:buildId/pitch-deck
 * Get pitch deck data
 */
router.get('/builds/:buildId/pitch-deck', requireUserAuth, verifyBuildOwnership, (async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.agent) {
      res.status(403).json({ error: 'No agent found for user' });
      return;
    }

    const { buildId } = req.params;

    // Get pitch deck
    const { data: pitchDeck, error: pitchError } = await getSupabase()
      .from('build_pitch_decks')
      .select('*')
      .eq('build_id', buildId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (pitchError && pitchError.code !== 'PGRST116') {
      throw pitchError;
    }

    res.json({
      pitchDeck: pitchDeck || null,
    });
  } catch (error) {
    console.error('Get pitch deck error:', error);
    res.status(500).json({
      error: 'Failed to get pitch deck',
      message: error instanceof Error ? error.message : 'unknown error',
    });
  }
}) as any);

export default router;
