-- ============================================================================
-- AGENT ORCHESTRATION SYSTEM
-- Tables for multi-agent build orchestration
-- ============================================================================

-- Agent Executions - Track agent task execution for each build
CREATE TABLE IF NOT EXISTS agent_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  build_id UUID NOT NULL REFERENCES generated_apps(id) ON DELETE CASCADE,
  agent_type TEXT NOT NULL CHECK (agent_type IN (
    'business_analyst',
    'financial_planner',
    'product_designer',
    'marketing',
    'legal',
    'technical_architect',
    'pitch'
  )),

  -- Execution status
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'completed', 'error')),
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  current_activity TEXT,

  -- Results
  result JSONB,
  error_message TEXT,

  -- Timing
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE(build_id, agent_type)
);

CREATE INDEX idx_agent_executions_build_id ON agent_executions(build_id);
CREATE INDEX idx_agent_executions_agent_type ON agent_executions(agent_type);
CREATE INDEX idx_agent_executions_status ON agent_executions(status);
CREATE INDEX idx_agent_executions_created_at ON agent_executions(created_at DESC);

-- Build Documents - Store documents generated by agents
CREATE TABLE IF NOT EXISTS build_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  build_id UUID NOT NULL REFERENCES generated_apps(id) ON DELETE CASCADE,

  -- Document metadata
  document_type TEXT NOT NULL, -- agent_type that generated it
  title TEXT NOT NULL,
  content JSONB NOT NULL,

  -- Versioning
  version INTEGER DEFAULT 1,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_build_documents_build_id ON build_documents(build_id);
CREATE INDEX idx_build_documents_document_type ON build_documents(document_type);
CREATE INDEX idx_build_documents_created_at ON build_documents(created_at DESC);

-- Build Spreadsheets - Financial models and data
CREATE TABLE IF NOT EXISTS build_spreadsheets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  build_id UUID NOT NULL REFERENCES generated_apps(id) ON DELETE CASCADE,

  -- Spreadsheet metadata
  spreadsheet_type TEXT NOT NULL DEFAULT 'financial_model',
  name TEXT,
  data JSONB NOT NULL,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_build_spreadsheets_build_id ON build_spreadsheets(build_id);
CREATE INDEX idx_build_spreadsheets_created_at ON build_spreadsheets(created_at DESC);

-- Build Pitch Decks - Investor pitch materials
CREATE TABLE IF NOT EXISTS build_pitch_decks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  build_id UUID NOT NULL REFERENCES generated_apps(id) ON DELETE CASCADE,

  -- Deck data compiled from all agents
  deck_data JSONB NOT NULL,

  -- Export formats
  pdf_url TEXT,
  pptx_url TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_build_pitch_decks_build_id ON build_pitch_decks(build_id);
CREATE INDEX idx_build_pitch_decks_created_at ON build_pitch_decks(created_at DESC);

-- Add completed_at column to generated_apps if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'generated_apps' AND column_name = 'completed_at'
  ) THEN
    ALTER TABLE generated_apps ADD COLUMN completed_at TIMESTAMPTZ;
  END IF;
END $$;

-- ============================================================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================================================

ALTER TABLE agent_executions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view agent executions for their builds"
  ON agent_executions FOR SELECT
  USING (
    build_id IN (
      SELECT id FROM generated_apps WHERE agent_id IN (
        SELECT id FROM agents WHERE user_id = auth.uid()
      )
    )
  );

CREATE POLICY "System can insert agent executions"
  ON agent_executions FOR INSERT
  WITH CHECK (true);

CREATE POLICY "System can update agent executions"
  ON agent_executions FOR UPDATE
  USING (true);

ALTER TABLE build_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view documents for their builds"
  ON build_documents FOR SELECT
  USING (
    build_id IN (
      SELECT id FROM generated_apps WHERE agent_id IN (
        SELECT id FROM agents WHERE user_id = auth.uid()
      )
    )
  );

CREATE POLICY "System can manage documents"
  ON build_documents FOR ALL
  USING (true);

ALTER TABLE build_spreadsheets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view spreadsheets for their builds"
  ON build_spreadsheets FOR SELECT
  USING (
    build_id IN (
      SELECT id FROM generated_apps WHERE agent_id IN (
        SELECT id FROM agents WHERE user_id = auth.uid()
      )
    )
  );

CREATE POLICY "System can manage spreadsheets"
  ON build_spreadsheets FOR ALL
  USING (true);

ALTER TABLE build_pitch_decks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view pitch decks for their builds"
  ON build_pitch_decks FOR SELECT
  USING (
    build_id IN (
      SELECT id FROM generated_apps WHERE agent_id IN (
        SELECT id FROM agents WHERE user_id = auth.uid()
      )
    )
  );

CREATE POLICY "System can manage pitch decks"
  ON build_pitch_decks FOR ALL
  USING (true);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply to all new tables
CREATE TRIGGER update_agent_executions_updated_at BEFORE UPDATE ON agent_executions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_build_documents_updated_at BEFORE UPDATE ON build_documents
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_build_spreadsheets_updated_at BEFORE UPDATE ON build_spreadsheets
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_build_pitch_decks_updated_at BEFORE UPDATE ON build_pitch_decks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
